# Generated by Django 2.1.4 on 2018-12-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koutuonline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='img',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
